
    alter table app_pr 
       drop 
       foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;

    alter table app_pr 
       drop 
       foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;

    alter table deploy 
       drop 
       foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;

    alter table sd_path 
       drop 
       foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;

    alter table sd_path 
       drop 
       foreign key if exists FKh7svn96p8c3k6x2e61guc61i;

    alter table sd_revision 
       drop 
       foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;

    alter table sub_project 
       drop 
       foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;

    alter table user 
       drop 
       foreign key if exists FK5npf04k4w955xmrh06bound7o;

    alter table user_role 
       drop 
       foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;

    alter table user_role 
       drop 
       foreign key if exists FK859n2jvi8ivhui0rl0esws6o;

    drop table if exists app_pr;

    drop table if exists deploy;

    drop table if exists project;

    drop table if exists role;

    drop table if exists sd_info;

    drop table if exists sd_path;

    drop table if exists sd_revision;

    drop table if exists sub_project;

    drop table if exists team;

    drop table if exists user;

    drop table if exists user_role;

    alter table app_pr 
       drop 
       foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;

    alter table app_pr 
       drop 
       foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;

    alter table deploy 
       drop 
       foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;

    alter table sd_path 
       drop 
       foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;

    alter table sd_path 
       drop 
       foreign key if exists FKh7svn96p8c3k6x2e61guc61i;

    alter table sd_revision 
       drop 
       foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;

    alter table sub_project 
       drop 
       foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;

    alter table user 
       drop 
       foreign key if exists FK5npf04k4w955xmrh06bound7o;

    alter table user_role 
       drop 
       foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;

    alter table user_role 
       drop 
       foreign key if exists FK859n2jvi8ivhui0rl0esws6o;

    drop table if exists app_pr;

    drop table if exists deploy;

    drop table if exists project;

    drop table if exists role;

    drop table if exists sd_info;

    drop table if exists sd_path;

    drop table if exists sd_revision;

    drop table if exists sub_project;

    drop table if exists team;

    drop table if exists user;

    drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
alter table app_pr drop foreign key if exists FK8cn4fkeqtfjl6vk4dun4ad0on;
alter table app_pr drop foreign key if exists FKd9wbcgmbhsnnuojwngr01htqp;
alter table deploy drop foreign key if exists FK2bqpm9s24tpffermy6ex4f30j;
alter table sd_path drop foreign key if exists FKiruo2utw2s3hla9dkbqi19o12;
alter table sd_path drop foreign key if exists FKh7svn96p8c3k6x2e61guc61i;
alter table sd_revision drop foreign key if exists FKhjpgx0syhkmeyvyscgc88i7vs;
alter table sub_project drop foreign key if exists FKgq7xf4xt3lbolay0gwnto1y3c;
alter table user drop foreign key if exists FK5npf04k4w955xmrh06bound7o;
alter table user_role drop foreign key if exists FK9x6fh31feadsw5ex9v5nn94h5;
alter table user_role drop foreign key if exists FK859n2jvi8ivhui0rl0esws6o;
drop table if exists app_pr;
drop table if exists deploy;
drop table if exists project;
drop table if exists role;
drop table if exists sd_info;
drop table if exists sd_path;
drop table if exists sd_revision;
drop table if exists sub_project;
drop table if exists team;
drop table if exists user;
drop table if exists user_role;
